version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - name=value
    env_file:
      - ./backend.env
    volumes:
      - ./:/app:rw
    container_name: appraiser
    depends_on:
      - postgres
    ports:
      - 81:81

  postgres:
    build:
      context: .
      dockerfile: dockerfile.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appraisal
    env_file:
      - ./postgres.env
    # networks:
    #   - appraiser-net
    # ports:
    #   - 3000:5432

volumes:
  db-data:
