version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - name=value
    # networks:
    #   - appraiser-net
    volumes:
      - ./:/app:ro
    container_name: appraiser
    depends_on:
      - postgres
    ports:
      - 81:81

  postgres:
    build:
      context: .
      dockerfile: dockerfile.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appraisal
    # networks:
    #   - appraiser-net
    ports:
      - 3000:5432

volumes:
  db-data:
