version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - name=value
    env_file:
      - ./backend.env
      - ./postgres.env
    volumes:
      - ./:/app:rw
    container_name: appraiser
    depends_on:
      - postgres
    ports:
      - 81:81

  postgres:
    build:
      context: .
      dockerfile: dockerfile.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appraisal
    env_file:
      - ./postgres.env
    ports:
      - 1164:5432

  pgadmin:
    build:
      context: .
      dockerfile: dockerfile.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 1165:80
      - 1166:443

volumes:
  db-data:
